/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZIilMmMOcdf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Workout, Exercise } from "@/lib/types";
import { JSX, SVGProps } from "react";
import { Checkbox } from "./ui/checkbox";
import { ArrowLeftIcon, ClockIcon } from "./icons";

const normalizeWorkout = (workout: Workout) => {
  // Create an empty object to store the grouped exercises
  const groupedByBodyPart: Record<string, Exercise[]> = {};

  // Iterate over the exercises array
  workout.excercises.forEach((exercise) => {
    // Check if the bodyPart is already a key in the grouped object
    if (!groupedByBodyPart[exercise.bodyPart]) {
      // If not, create an array for this body part
      groupedByBodyPart[exercise.bodyPart] = [];
    }
    // Add the exercise to the correct body part array
    groupedByBodyPart[exercise.bodyPart].push(exercise);
  });

  return groupedByBodyPart;
};

export function WorkoutDetail({ workout }: { workout: Workout }) {
  const excercises = normalizeWorkout(workout);
  return (
    <div className="flex flex-col min-h-screen bg-gray-900">
      <header className="bg-red-600 text-gray-200 py-4 px-6 flex items-center">
        <Link className="mr-4" href="/">
          <ArrowLeftIcon className="h-6 w-6" />
        </Link>
        <h1 className="text-2xl font-bold">{workout.name}</h1>
      </header>
      <main className="flex-1 bg-gray-900 p-4 sm:p-6">
        <div className="max-w-4xl mx-auto">
          <section className="bg-[#1F2937] rounded-2xl shadow-md p-4 sm:p-6 mb-4 sm:mb-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl font-bold text-gray-200">Exercises</h2>
              <div className="text-gray-400">
                <ClockIcon className="mr-2 h-5 w-5 inline" />
                <span>{workout.duration} mins</span>
              </div>
            </div>
            <div className="grid gap-4 sm:gap-6">
              {Object.entries(excercises).map(([name, list]) => (
                <div className="bg-[#1F2937] rounded-2xl p-4 sm:p-6" key={name}>
                  <h3 className="text-lg font-bold text-gray-200">{name}</h3>
                  <ul className="space-y-2 mt-2">
                    {list.map((excercise) => (
                      <li
                        className="flex items-center justify-between gap-4"
                        key={excercise.name}
                      >
                        <div className="flex flex-col">
                          <span className="text-gray-400">
                            {excercise.name} ({excercise.sets} x{" "}
                            {excercise.reps})
                          </span>
                          <span className="text-gray-400 text-xs">
                            {excercise.description}
                          </span>
                        </div>
                        <Checkbox />
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
